name: DEV NPM Build Version Publish

on: 
  push:
    branches:
    - dev
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build

  version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --global user.name '[Workflow]'
      - run: git config --global user.email '<>'
      - run: npm version patch -m "[DEV] %s"
      - run: git push

  publish:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}