name: DEV_NPM_Build_Version

on: 
  push:
    branches:
    - dev
    paths-ignore:
      - '.github/**'
    
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build

  version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --global user.name '[Workflow]'
      - run: git config --global user.email '<>'
      - run: npm version patch -m "[DEV] %s"
      - run: git push