name: DEV_NPM_Publish

on:
  workflow_run:
    workflows: ["DEV_NPM_Version"]
    branches: [dev]
    types: [completed]
    
jobs:

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dev'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
