name: DEV NPM Publish

on: 
  push:
    branches:
    - dev
    paths-ignore:
      - '.github/**'
    
jobs:

  publish:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
