name: DEV NPM Version

on:
  workflow_run:
    workflows: ["DEV Build Push"]
    branches: [dev]
    types: 
      - completed

jobs:

  version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --global user.name '[Github Bot]'
      - run: git config --global user.email '<>'
      - run: npm version patch -m "[DEV] %s"
      - run: git push
