name: DEV_NPM_Version

on:
  workflow_run:
    workflows: ["DEV_Build_Push"]
    branches: [dev]
    types: [completed]

jobs:

  version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --global user.name '[Workflow]'
      - run: git config --global user.email '<>'
      - run: npm version patch -m "[DEV] %s"
      - run: git push
